### PR TITLE
Add Vsync Mode option

### PR DESCRIPTION
**Pull request by the-furry-hubofeverything**
I had some choppiness with how the window rendered, and saw that VSync is disabled, so I decided to make it available as an option in the window setting.

lmk if that's a good place to put it

### CODE REVIEW

**Comment by LainAmongYou** [comment]
@the-furry-hubofeverything @ExpiredPopsicle How do you both feel about making this setting on by default? Feels weird being off by default.

**Comment by the-furry-hubofeverything** [comment]
> @the-furry-hubofeverything @ExpiredPopsicle How do you both feel about making this setting on by default? Feels weird being off by default.

I think it should be left to the user, because VSync introduces a little bit of input lag, and SnekStudio might not as performant on certain computers.

**Comment by LainAmongYou** [comment]
Hmm. Actually let me do a double take for a minute and ask for some clarification about the issue.

1. When you say choppiness, you do mean tearing right?
2. If SnekStudio was being captured by a streaming/capture software (e.g. OBS), was the choppiness you mentioned also happening in the capture?
3. Sometimes people make PRs for things they notice while trying to fix some specific issue even though they don't fix that specific issue, so I originally assumed that when you made this PR, that this issue was fixed by this change. However, I just realized you did not state whether this change did or not. Could you confirm that just to be safe?

I apologize if this seems like I'm interrogating you or something, this doesn't really have anything to do with whether this feature should be merged (it probably should be), but just information I realized that would be good to know.

**Comment by the-furry-hubofeverything** [comment]
> Thank you very much for explaining!
> 
> I might have misunderstood originally, I thought you were wanting to disable v-sync by default, personally I was advocating for v-sync to be enabled by default and letting the user opt to disable it if desired. Your PR disables seems to disable it by default.
> 
> Just led me to be a bit concerned about potential capture issues due to v-sync being disabled by default. I probably should have said that from the beginning, so I apologize. Mostly I'm just wanting to make sure there are no capture issues.

It was disabled by default because originally, the program was set so that VSync was off. It was to preserve default behavior

**Comment by LainAmongYou** [comment]
Oh it was? I thought it was the other way around the entire time. Nevermind then, sorry again for taking too much of your time (also thank you again for taking the time to clear those things up! Those things are good to know in either case.)

**Comment by ExpiredPopsicle** [comment]
Hey sorry it took me a month to get to merging this one. Thanks for the PR!

**Pull request merged**
