### PR TITLE
Add face blendshape calibration

### PR DESCRIPTION
**Pull request by the-furry-hubofeverything**
Record then average the blendshape values and then subtracting it from mediapipe output.

I have a "resting bitch face" and so my lips always seems puckered.

this will skip any eye blendshapes.

### CODE REVIEW

**Comment by the-furry-hubofeverything** [comment]
https://github.com/user-attachments/assets/dbf5b0f7-c420-470b-9536-29364c814837

**Comment by copygirl** [comment]
> this will skip any eye blendshapes.

Not a solution for my eyes generally not staying open then? :sweat_smile:

**Comment by the-furry-hubofeverything** [comment]
> > this will skip any eye blendshapes.
> 
> Not a solution for my eyes generally not staying open then? 😅

@copygirl I skipped eye blendshapes because the blendshapes for gaze (up, down, left and right) are not easy to calibrate with. Eyes move all the time. 

But I think eyelids can be added to the calibration.

**Comment by the-furry-hubofeverything** [comment]
> > this will skip any eye blendshapes.
> 
> Not a solution for my eyes generally not staying open then? 😅

@copygirl After a quick experiment, I think eyelid calibration should be a separate thing, or at least the calibration process needs to be more accurate before then. When I include the eyelids, my model stops blinking. 

So, I think that might be a future problem. Maybe as a multiplier of some sort.

**Pull request merged**
